### ISSUE TITLE
VS 2022 prerequisites cannot be resolved

### ISSUE THREAD

**Issue by rober423** [stickleprojects/ClassOutline#20]
Downloaded vsix from v2.0.1 and this happened
![image](https://github.com/FireflyMigration/ClassOutline/assets/42657833/51aaeeb7-f793-4758-a31e-59e13de2a91e)

**Comment by noam-honig** [comment]
I had the same issue. Updating to the latest version of vs2022 solved it.

I'm on version 17.5.4

**Comment by rober423** [comment]
My VS2022 is 17.6.0

**Comment by chris-cashin** [comment]
I have the same issue with a fresh install of VS2022 17.6.3 on either Windows 11 Enterprise or Server 2022
I tired installing the Firefly Visual Studio 2022 Templates first as well thinking maybe something from there was required as well. I was so looking forward to this feature

**Comment by noam-honig** [comment]
Hi @rober423 & @chris-cashin I think I've fixed it, can you check at:

https://github.com/FireflyMigration/ClassOutline/releases/tag/v2022.2.0.2


Let me know

**Comment by chris-cashin** [comment]
Works like a charm in both the latest and preview versions of VS2022.
Many Thanks

**Comment by noam-honig** [comment]
I actually didn't know that.

I use class outline, as a window, here's a video:

https://doc.fireflymigration.com/using-class-outline-to-read-large-controller-trees.html
